server:
  port: 9090
spring:
  datasource:
    url: jdbc:mysql://139.224.74.226:3306/ryx365?useUnicode=true&amp;characterEncoding=utf8
    username: ryxuser
    password: Ryxuser123456!!!!
    driver-class-name: com.mysql.jdbc.Driver
