server:
  port: 9090
spring:
  datasource:
    url: jdbc:mysql://139.224.74.226:3306/ryx365?useUnicode=true&amp;characterEncoding=utf8
    username: ryxuser
    password: Ryxuser123456!!!!
    driver-class-name: com.mysql.jdbc.Driver
    thymeleaf:
      prefix: classpath:/templates/
      suffix: .html
      encoding: UTF-8
      content-type: text/html
      cache: false
      mode: HTML5

mybatis:
  mapper-locations: classpath:mapping/**/*.xml
  type-aliases-package: com.king.nowedge.dto
